// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPCXU549EFD9onIS71RGKQnG-UXpljQtQ',
    appId: '1:23269018483:web:9c3ac64040dfbbf25b9306',
    messagingSenderId: '23269018483',
    projectId: 'main-command-408703',
    authDomain: 'main-command-408703.firebaseapp.com',
    storageBucket: 'main-command-408703.appspot.com',
    measurementId: 'G-13QSHKCPD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFCI1mBMPbde1-nj2poxsm2gL3jE4q61I',
    appId: '1:23269018483:android:c6c35478b54ee4455b9306',
    messagingSenderId: '23269018483',
    projectId: 'main-command-408703',
    storageBucket: 'main-command-408703.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoOrr66yI19uyoXCG0-hsUOI49Ya__02k',
    appId: '1:23269018483:ios:0d9098298832e26d5b9306',
    messagingSenderId: '23269018483',
    projectId: 'main-command-408703',
    storageBucket: 'main-command-408703.appspot.com',
    iosBundleId: 'com.example.firebaseNotifications',
  );
}
